# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-31 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('completado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Fila',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('numero_fila', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoRegresionMultiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('objetivos', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_final', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.BooleanField(default=False)),
                ('moderador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regresion_multiple_moderador', to=settings.AUTH_USER_MODEL, verbose_name='moderador_regresion_multiple')),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=10)),
                ('filas', models.ManyToManyField(to='regresion_multiple.Fila')),
            ],
        ),
        migrations.AddField(
            model_name='estudio',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regresion_multiple_estudio', to='regresion_multiple.ProyectoRegresionMultiple', verbose_name='estudio_regresion_multiple'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='variable_dependiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regresion_multiple_variable_dependiente', to='regresion_multiple.Variable'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='variables_independientes',
            field=models.ManyToManyField(related_name='regresion_multiple_variables_dependientes', to='regresion_multiple.Variable'),
        ),
    ]
